<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
    <div style="float:right;">
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a class="n2lbox-albinfoboxlink" href="<?php echo $this->url(array('page' => $this->first)); ?>">
      <?= $this->translate('First');?> </a> |
<?php else: ?>
  <span class="disabled"><?= $this->translate('First');?></span> |
<?php endif; ?>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a class="n2lbox-albinfoboxlink" href="<?php echo $this->url(array('page' => $this->previous)); ?>"> &lt; <?= $this->translate('Previous');?>  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?= $this->translate('Previous');?></span> |
<?php endif; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a class="n2lbox-albinfoboxlink" href="<?php echo $this->url(array('page' => $this->next)); ?>">  <?= $this->translate('Next');?> &gt; </a> |
<?php else: ?>
  <span class="disabled"><?= $this->translate('Next');?> &gt;</span> |
<?php endif; ?>
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a class="n2lbox-albinfoboxlink" href="<?php echo $this->url(array('page' => $this->last)); ?>">  <?= $this->translate('Last');?>  </a>
<?php else: ?>
  <span class="disabled"><?= $this->translate('Last');?></span>
<?php endif; ?>
  </div>
    <div>
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
 <?= $this->translate('of')?> <?php echo $this->totalItemCount; ?></div>
</div>
<?php endif;?>