<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a rel="prev" href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): $rel = $page > $this->current ? 'next' : 'prev';?>
    <a  rel="<?= $rel ?>" href="<?= $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> |
  <?php else: ?>
    <span id="current_page"><?php echo $page; ?></span> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a rel="next" href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>