<div id="rCol">    
    <div class="n2s-grid-5">
        <div id="modBlock">
            <?= $this->userWriteMessage(); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="n2s-grid-6">
        <?= $this->html; ?>
        <div id="timeContent">
            <div id="timeArrey"></div>
            <div id="ajaxload">
                <img src="/images/ajax/ajax-loader1.gif" alt=""/>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="UsersCheck" value=""/>

<script  type="text/javascript">
var aSuppressScroll = false;
var bSuppressScroll = false;
$(function(){
    $(window).load(function() {
        if ($('#timeContent').height() < $(window).height()){
            $('#timeContent').css('min-height', $(window).height()+'px');
            var flink = '/community/messages/list<?= $this->link;?>';
            message.first(flink);
        }
    });
    $(window).scroll(function(){
        if (($(window).scrollTop() >= $('body').height() - $(window).height()-600) && window.bSuppressScroll == false && window.aSuppressScroll == true){
            $('#ajaxload').show();
            var linkscroll = '/community/messages/list<?= $this->link;?>';
            message.next(linkscroll);
            window.bSuppressScroll = true;
        }
    });
});
</script>