<div id="rCol">
    <div class="n2s-grid-5">
        <div id="modBlock">
            <?= $this->userWriteMessage(); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="n2s-grid-6">
        <?= $this->html; ?>
        <div id="timeContent">
            <div id="timeArrey">
                <?= $this->dataContainer; ?>
            </div>
            <div id="ajaxload" style="margin-top: 30px;">
                <img src="/images/ajax/ajax-loader1.gif" alt=""/>
            </div>
        </div>
    </div>
</div>

<script  type="text/javascript">
var aSuppressScroll = false;
var bSuppressScroll = false;
$(function(){
    $(window).load(function() {
        if ($('#timeContent').height() < $(window).height()){
            $('#timeContent').css('min-height', $(window).height()+'px');
            var flink = '/community/messages/list/view/<?= $this->show; ?>';
            message.first(flink);
        }
    });
    $(window).scroll(function(){
        if (($(window).scrollTop() >= $('body').height() - $(window).height()-600) && window.bSuppressScroll === false && window.aSuppressScroll === true){
            $('#ajaxload').show();
            var linkscroll = '/community/messages/list/view/<?= $this->show; ?>';
            message.next(linkscroll);
            window.bSuppressScroll = true;
        }
        if ($(window).scrollTop() > $('.n2s-main').offset().top+64){
            var lpr = $('#msgWriter').height()+36;
            $('#msgWriter').css({'position': 'fixed','top':'0'});
            $('#h1').css('margin', '16px 0 '+lpr+'px');
        }
        if ($(window).scrollTop() <= $('.n2s-main').offset().top+64){
            $('#msgWriter').css('position', 'inherit');
            $('#h1').css('margin', '16px 0px');
        }
    });
});
</script>