<div id="rCol">
    <div class="n2s-grid-5">
        <div id="modBlock">
            <?= $this->userMaybeFriends(); ?>
            <div class="clear"></div>
            <?= $this->reklame(); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="n2s-grid-6">
        <div id="timeMessage"></div>
        <?= $this->html; ?>
        <div id="timeContent">
            <div id="timeArrey"></div>
            <div id="ajaxload">
                <img src="/images/ajax/ajax-loader1.gif" alt=""/>
            </div>
        </div>
    </div>
</div>

<script  type="text/javascript">
var flink='/venues/index/<?= $this->link;?>';
var aSuppressScroll=false;
var bSuppressScroll=false;
var flistsearch=true;
var slistsearch=true;
var navData="";
var unvisib="";
$(function(){
    $(window).load(function() {
        if ($('#timeContent').height() < $(window).height()){
            $('#timeContent').css('min-height', $(window).height()+'px');
            list.first(flink);
        }
    });
});

    $(window).scroll(function(){
        list.navi();
        if(($(window).scrollTop()>=$('body').height()-$(window).height()-600)&&window.bSuppressScroll==false&&window.aSuppressScroll==true){
            $('#ajaxload').show();
            var time=$('.LBox:last').attr('id');
            var li = flink+time;
            if($('#geo').length)
                li = li+'/geosearch/'+$('#geo').val();
            list.next(li);
            window.bSuppressScroll=true;
        }
        if($(window).scrollTop()>$('.n2s-main').offset().top+$('#modBlock').height()){
            $('#dateNaviLink').css({'position':'fixed','top':'0'});
        }
        if($(window).scrollTop()<=$('.n2s-main').offset().top+$('#modBlock').height()){
            $('#dateNaviLink').css('position', 'inherit');
        }
    });

//GeoSwitch
$(document).click(function(event){
    if(($(event.target).parents().index($('#geosearcher'))==-1)&&($('#geosearchinput').is(":visible"))){
        $('#geosearchinput').hide();
        $("#geosearchposition").show();
        $("#resetLocButton").show();
    }
    if(($(event.target).parents().index($('#geosearchposition'))==0||$(event.target).parents().index($('#geosearcher'))==0)&&$('#geosearchinput').is(":hidden")){
        $("#geosearchposition").hide();
        $("#resetLocButton").hide();
        $("#geosearchinput").show();
        $('input[name=geosearch]').focus();
        $('input[name=geosearch]').keypress(function(e){
            if(e.which==13){
                geosearch.find(flink);
            }
        });
        }
        });
</script>