<div id="rCol">    
    <div class="n2s-grid-5">
        <div id="modBlock">
            <?= $this->userMaybeFriends(); ?>
            <div class="clear"></div>
            <?= $this->reklame(); ?>
            <div class="clear"></div>
        </div>
        <div id="dateNaviLink" style="position: inherit;"></div>
    </div>
    <div class="n2s-grid-6">
        <?= $this->link; ?>
        <h1><?= $this->titel; ?></h1>
        <?= $this->html; ?>
    </div>
</div>